version: '3.8'

services:
  app:
    container_name: ${SERVICE}
    image: ${REGISTRY_URL}/${USER_NAME}/${SERVICE}
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    env_file:
      - .env
    ports:
      - ${PORT:-8000}:8000
