services:
  - type: web
    name: qaas-web
    runtime: docker
    repo: https://github.com/pythoninthegrass/qaas.git      # optional
    branch: main
    pullRequestPreviewsEnabled: true                        # optional
    autoDeploy: true                                        # optional
    domains:
      - qaas.sh
    plan: starter                                           # free/starter/standard
    region: ohio                                            # oregon, ohio, frankfurt, or singapore
    disk:                                                   # starter/standard only
      name: web-data
      mountPath: /app
      sizeGB: 5
    registryCredential:                                     # https://dashboard.render.com/u/settings#registry-credentials
      fromRegistryCreds:
        name: GITHUB_TOKEN
    rootDir:                                                # default: top-level directory
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /healthz
    envVars:
      - fromGroup: qaas-settings
      - key: PORT
        value: 8000
      - key: POSTGRES_URI
        fromDatabase:
          name: qaas-postgres
          property: connectionString

databases:
  - name: qaas-postgres
    databaseName: quotes                                    # optional (Render may add a suffix)
    user: sa                                                # optional
    region: ohio                                            # oregon, ohio, frankfurt, or singapore
    postgresMajorVersion: 15                                # 12/13/14/15
    plan: free                                              # free/starter/standard
    ipAllowList:                                            # default: allow all (empyty list `[]` is internal only)
      - source: 172.16.0.0/24
        description: home

envVarGroups:
- name: qaas-settings
  envVars:
    - key: POSTGRES_DB
      sync: false
    - key: POSTGRES_HOST
      sync: false
    - key: POSTGRES_PASSWORD
      sync: false
    - key: POSTGRES_PORT
      sync: false
    - key: POSTGRES_USER
      sync: false
    - key: REGISTRY_URL
      value: ghcr.io
    - key: SERVICE
      sync: false
    - key: USER_NAME
      sync: false
