services:
  - type: web
    name: qaas-web
    runtime: docker
    repo: https://github.com/pythoninthegrass/qaas.git      # optional
    branch: main
    autoDeploy: false                                       # optional
    domains:
      - qaas.sh
    plan: free                                              # free/starter/standard
    region: ohio                                            # oregon, ohio, frankfurt, or singapore
    # disk:                                                 # starter/standard only
    #   name: web-data
    #   mountPath: /app
    #   sizeGB: 5
    registryCredential:                                     # https://dashboard.render.com/u/settings#registry-credentials
      fromRegistryCreds:
        name: GITHUB_TOKEN
    rootDir:
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8000
      - key: POSTGRES_DB
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: qaas-postgres
    databaseName: quotes                                    # optional (Render may add a suffix)
    user: postgres                                          # optional
    region: ohio                                            # oregon, ohio, frankfurt, or singapore
    postgresMajorVersion: 15                                # 12/13/14/15
    plan: free                                              # free/starter/standard
    ipAllowList:                                            # default: allow all (empyty list `[]` is internal only)
      - source: 172.127.40.244/24
        description: home
    envVars:
      - key: POSTGRES_URI
        fromDatabase:
          name: qaas-postgres
          property: connectionString
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
