version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  TLD:
    sh: git rev-parse --show-toplevel
  COMPOSE_FILE: docker-compose.yml
  NETWORK: app-tier

vars:

includes:
  docker:
    taskfile: ./tasks/docker.yml
    aliases: ["docker"]
  poetry:
    taskfile: ./tasks/poetry.yml
    aliases: ["poetry"]

tasks:
  print:
    - |
      echo -e "TLD:\t\t$TLD"
      echo -e "REGISTRY_URL:\t$REGISTRY_URL"
      echo -e "USER_NAME:\t$USER_NAME"
      echo -e "SERVICE:\t$SERVICE"

  default:
    desc: "Default task"
    cmds:
      - task --list

  json-to-postgres:
    desc: "Upload quotes to postgres from json"
    cmds:
      - "{{.TLD}}/bin/json_to_postgres.py db.json"

  sqlite-to-postgres:
    desc: "Upload quotes to postgres from sqlite"
    cmds:
      - "{{.TLD}}/bin/sqlite_to_postgres.py db.sqlite"
