name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted

  check_suite:
    types:
      - completed

  status: {}

permissions:
  contents: write

env:
  MERGE_LABELS: "autorelease: pending"
  MERGE_REMOVE_LABELS: "automerge, autorelease: pending"
  MERGE_METHOD: "squash"
  MERGE_REQUIRED_APPROVALS: 0
  MERGE_RETRIES: "3"
  MERGE_RETRY_SLEEP: "10000"

  # labels that need to be present for a pull request to be updated
  # * updating will only happen when the option "Require branches to be up to date before merging" is enabled in the branch protection rules
  UPDATE_LABELS: ""
  UPDATE_METHOD: "rebase"

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "DEBUG"  # DEBUG, INFO, WARN, ERROR, TRACE

      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
